language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.1
    - android-25

    - add-on
    - extra

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble
